# Generated by Django 4.1.7 on 2023-03-25 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text2touch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='prompt',
            field=models.CharField(default='', max_length=64, verbose_name='prompt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prompt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL),
        ),
    ]
