# Generated by Django 4.1.7 on 2023-03-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text2touch', '0002_prompt_prompt_alter_prompt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='method',
            field=models.CharField(choices=[('GPT3', 'GPT-3'), ('DALLE2', 'DALL·E 2')], default='GPT3', max_length=8, verbose_name='method'),
            preserve_default=False,
        ),
    ]
