# Generated by Django 4.1.7 on 2023-03-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text2touch', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='pov',
            field=models.CharField(choices=[('SIDE', 'Side view'), ('FRONT', 'Front view'), ('TOP', 'Top view')], default='SIDE', max_length=16, verbose_name='point of view'),
        ),
    ]
